# Generated by Django 2.2.2 on 2020-05-07 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Art', 'Art'), ('Lecture', 'Lecture'), ('Picnic', 'Picnic')], max_length=20)),
                ('unit_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='ComposantRepas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrecheChild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regno', models.CharField(max_length=6, unique=True)),
                ('names', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True)),
                ('group', models.CharField(choices=[('Grand', 'Grand'), ('Petit', 'Petit')], default='Petit', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kid',
            },
        ),
        migrations.CreateModel(
            name='CrechePrincipal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('identity_document', models.CharField(max_length=50, unique=True)),
                ('full_addres', models.TextField(blank=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('Accueillabte', 'Accueillabte'), ('Directrice', 'Directrice'), ('Directeur', 'Directeur')], default='Accueillante', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'principal',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=192, unique=True)),
                ('is_public', models.IntegerField()),
                ('template_path', models.CharField(max_length=765)),
                ('parameter', models.CharField(blank=True, max_length=765)),
                ('from_email', models.CharField(max_length=765)),
                ('group_text', models.CharField(blank=True, max_length=96)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_type',
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by_id', models.IntegerField()),
                ('ip_address', models.CharField(max_length=765)),
                ('logout_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_audit',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('display_name', models.CharField(max_length=96)),
                ('handler', models.CharField(max_length=192)),
                ('icon_file', models.CharField(max_length=96)),
                ('description', models.CharField(max_length=765)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='WebEmailAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latest_test', models.DateTimeField(auto_now_add=True)),
                ('issue_number', models.IntegerField()),
                ('is_abort', models.IntegerField()),
                ('prepared_at', models.DateTimeField()),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('email_body', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'web_email_audit',
            },
        ),
        migrations.CreateModel(
            name='WebUserDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('full_name', models.CharField(blank=True, max_length=192, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_use_admin', models.IntegerField(default=False)),
                ('alert_frequency', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'web_user_detail',
            },
        ),
        migrations.CreateModel(
            name='WebUsers',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('pass_field', models.CharField(db_column='pass', max_length=384)),
                ('mail', models.CharField(blank=True, max_length=762)),
                ('theme', models.CharField(max_length=765)),
                ('signature', models.CharField(max_length=765)),
                ('signature_format', models.CharField(blank=True, max_length=765)),
                ('created', models.IntegerField()),
                ('access', models.IntegerField()),
                ('login', models.IntegerField()),
                ('status', models.IntegerField()),
                ('timezone', models.CharField(blank=True, max_length=96)),
                ('language', models.CharField(max_length=36)),
                ('init', models.CharField(blank=True, max_length=762)),
                ('data', models.TextField(blank=True)),
                ('picture', models.IntegerField()),
                ('uuid', models.CharField(max_length=108)),
            ],
            options={
                'db_table': 'web_users',
            },
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Module')),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.WebUsers')),
            ],
            options={
                'db_table': 'user_module_perm',
            },
        ),
        migrations.CreateModel(
            name='SystemUserEventType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type_id', models.IntegerField()),
                ('system_user_id', models.IntegerField()),
                ('can_unsubscribe', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'system_user_has_event_type',
                'unique_together': {('event_type_id', 'system_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('menu', models.ManyToManyField(related_name='components', to='coreapp.ComposantRepas')),
            ],
            options={
                'db_table': 'repas',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_reference_id', models.IntegerField(blank=True, null=True)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('processed', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.EventType')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to_email', models.CharField(max_length=765)),
                ('scheduled_for_relay', models.IntegerField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('from_email', models.CharField(max_length=765)),
                ('subject', models.CharField(blank=True, max_length=192)),
                ('message_body', models.TextField(blank=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Event')),
            ],
            options={
                'db_table': 'email_schedule',
            },
        ),
        migrations.CreateModel(
            name='DailyChildReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('day_price', models.FloatField(default=7.5)),
                ('accueillante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.CrechePrincipal')),
                ('activities', models.ManyToManyField(related_name='activities', to='coreapp.ChildActivity')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.CrecheChild')),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Repas')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='CrecheParent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('identity_document', models.CharField(max_length=50, unique=True)),
                ('full_addres', models.TextField(blank=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], default='Guardian', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('children', models.ManyToManyField(related_name='parents', to='coreapp.CrecheChild')),
            ],
            options={
                'db_table': 'guardian',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=12, unique=True)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.CrecheChild')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
    ]
