# Generated by Django 2.2.2 on 2020-05-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='composantrepas',
            table='patisserie',
        ),
    ]
