# Generated by Django 2.2.2 on 2020-05-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
Nadia   ('coreapp', '0001_initial'),
    ]

    operations = [
Nadia   migrations.AlterModelTable(
NadiaNadia  name='composantrepas',
NadiaNadia  table='patisserie',
Nadia   ),
    ]
