# Generated by Django 2.2.2 on 2020-05-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20200507_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crecheparent',
            old_name='full_addres',
            new_name='full_address',
        ),
        migrations.RenameField(
            model_name='crecheprincipal',
            old_name='full_addres',
            new_name='full_address',
        ),
        migrations.AlterField(
            model_name='crecheprincipal',
            name='role',
            field=models.CharField(choices=[('Accueillante', 'Accueillante'), ('Directrice', 'Directrice'), ('Directeur', 'Directeur'), ('Teacher', 'Teacher')], default='Accueillante', max_length=20),
        ),
    ]
